# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rspec-tag_matchers}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{David Cuddeback}]
  s.date = %q{2012-04-02}
  s.description = %q{A collection of RSpec matchers that understand Rails conventions, allowing for more concise specs.}
  s.email = %q{david.cuddeback@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "Guardfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "core_ext/deep_flattening.rb",
    "lib/rspec-tag_matchers.rb",
    "lib/rspec/tag_matchers.rb",
    "lib/rspec/tag_matchers/has_checkbox.rb",
    "lib/rspec/tag_matchers/has_date_select.rb",
    "lib/rspec/tag_matchers/has_form.rb",
    "lib/rspec/tag_matchers/has_input.rb",
    "lib/rspec/tag_matchers/has_select.rb",
    "lib/rspec/tag_matchers/has_tag.rb",
    "lib/rspec/tag_matchers/has_time_select.rb",
    "lib/rspec/tag_matchers/helpers/sentence_helper.rb",
    "lib/rspec/tag_matchers/multiple_input_matcher.rb",
    "rspec-tag_matchers.gemspec",
    "spec/core_ext/deep_flattening_spec.rb",
    "spec/lib/rspec/tag_matchers/has_checkbox_spec.rb",
    "spec/lib/rspec/tag_matchers/has_date_select_spec.rb",
    "spec/lib/rspec/tag_matchers/has_form_spec.rb",
    "spec/lib/rspec/tag_matchers/has_input_spec.rb",
    "spec/lib/rspec/tag_matchers/has_select_spec.rb",
    "spec/lib/rspec/tag_matchers/has_tag_spec.rb",
    "spec/lib/rspec/tag_matchers/has_time_select_spec.rb",
    "spec/lib/rspec/tag_matchers/multiple_input_matcher_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/dcuddeback/rspec-tag_matchers}
  s.licenses = [%q{MIT}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.6}
  s.summary = %q{RSpec matchers for Rails views}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<guard>, [">= 0"])
      s.add_development_dependency(%q<guard-rspec>, [">= 0"])
      s.add_development_dependency(%q<guard-bundler>, [">= 0"])
    else
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<guard>, [">= 0"])
      s.add_dependency(%q<guard-rspec>, [">= 0"])
      s.add_dependency(%q<guard-bundler>, [">= 0"])
    end
  else
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<guard>, [">= 0"])
    s.add_dependency(%q<guard-rspec>, [">= 0"])
    s.add_dependency(%q<guard-bundler>, [">= 0"])
  end
end

